config/routes.rb
Rottenpotatoes::Application.routes.draw do

  resources :movies
  match "samed" => "movies#samed"

end

app/models/movie.rb
class Movie < ActiveRecord::Base
  attr_accessible :title, :rating, :description, :release_date, :director
  def self.get_all_ratings
  	Movie.select("DISTINCT rating").map(&:rating)
  end
  
  def self.finddir(string)
    Movie.where(["director = ?", string])
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController

  def show
    id = params[:id] # retrieve movie ID from URI route
    @movie = Movie.find(id) # look up movie by unique ID
    # will render app/views/movies/show.<extension> by default
  end

  def index
    sort = params[:sort] || session[:sort] 
    @all_ratings = Movie.get_all_ratings
    x = false

    ratings = params[:ratings] || session[:ratings] || {}
    if ratings != {}
      @ratings = ratings
    else
      @ratings = Hash.new
      @all_ratings.each {|r| @ratings[r] = 1}
    end
    if params[:ratings]
      session[:ratings] = @ratings
    elsif session[:ratings]
      x = true
    end
    
    if params[:sort]
      session[:sort] = sort
    elsif session[:sort]
      x = true
    end

    if x
      redirect_to :sort => sort, :ratings => @ratings
    end

    if sort == "title"
      @movies = Movie.where(rating: @ratings.keys).order("title")
      @title = "hilite"
    elsif sort == "date"
      @movies = Movie.where(rating: @ratings.keys).order("release_date")
      @date = "hilite"
    else
      @movies = Movie.where(rating: @ratings.keys)
    end
  end

  def new
    # default: render 'new' template
  end

  def create
    @movie = Movie.create!(params[:movie])
    flash[:notice] = "#{@movie.title} was successfully created."
    redirect_to movies_path
  end

  def edit
    @movie = Movie.find params[:id]
  end

  def update
    @movie = Movie.find params[:id]
    @movie.update_attributes!(params[:movie])
    flash[:notice] = "#{@movie.title} was successfully updated."
    redirect_to movie_path(@movie)
  end

  def destroy
    @movie = Movie.find(params[:id])
    @movie.destroy
    flash[:notice] = "Movie '#{@movie.title}' deleted."
    redirect_to movies_path
  end

  def samed
    
    if params[:director].nil? || params[:director].length == 0
      flash[:notice] = "'#{params[:title]}' has no director info"
      redirect_to movies_path
    end
    @movies = Movie.finddir(params[:director])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.haml
!!! 5
%html
  %head
    %title Rotten Potatoes!
    = stylesheet_link_tag 'application'
    = javascript_include_tag 'application'
    = csrf_meta_tags

  %body
    %h1.title Rotten Potatoes!
    #main
      - if flash[:notice]
        #notice.message= flash[:notice]
      - elsif flash[:warning]
        #warning.message= flash[:warning]

      = yield

app/views/movies/edit.html.haml
-# edit.html.haml using partial

%h1 Edit Existing Movie

= form_tag movie_path(@movie), :method => :put do

  = label :movie, :title, 'Title'
  = text_field :movie, 'title'

  = label :movie, :rating, 'Rating'
  = select :movie, :rating, ['G','PG','PG-13','R','NC-17']

  = label :movie, :release_date, 'Released On'
  = date_select :movie, :release_date

  = label :movie, :director, 'Director'
  = text_field :movie, 'director'
  
  = submit_tag 'Update Movie Info'

app/views/movies/index.html.haml
-#  This file is app/views/movies/index.html.haml

= form_tag movies_path, :id => "ratings_form", :method => :get do
  Include: 
  - @all_ratings.each do |rating|
    = rating
    = check_box_tag "ratings[#{rating}]", @ratings[rating], @ratings[rating] ? true : false, :id => "ratings_#{rating}"
  = submit_tag 'Refresh', :id=>"ratings_submit"


%h1 All Movies

%table#movies
  %thead
    %tr
      %th{:class => @title}= link_to "Movie Title", movies_path({:sort => "title"}), :id => "title_header"
      %th Rating
      %th Director
      %th{:class => @date}= link_to "Release Date", movies_path({:sort => "date"}), :id => "release_date_header"
      %th More Info
  %tbody
    - @movies.each do |movie|
      %tr
        %td= movie.title 
        %td= movie.rating
        %td= movie.director
        %td= movie.release_date
        %td= link_to "More about #{movie.title}", movie_path(movie)

= link_to 'Add new movie', new_movie_path

app/views/movies/new.html.haml
%h1 Create New Movie

= form_tag movies_path do

  = label :movie, :title, 'Title'
  = text_field :movie, 'title'

  = label :movie, :rating, 'Rating'
  = select :movie, :rating, ['G','PG','PG-13','R','NC-17']

  = label :movie, :release_date, 'Released On'
  = date_select :movie, :release_date

  = submit_tag 'Save Changes'

app/views/movies/samed.html.haml
%h1 Same Director

%table#movies
  %thead
    %tr
      %th Movie Title
      %th Rating
      %th Director
      %th Release Date
      %th More Info
  %tbody
    - @movies.each do |movie|
      %tr
        %td= movie.title 
        %td= movie.rating
        %td= movie.director
        %td= movie.release_date
        %td= link_to "More about #{movie.title}", movie_path(movie)

= link_to 'Add new movie', new_movie_path
= link_to 'Back to movie list', movies_path

app/views/movies/show.html.haml
-# in app/views/movies/show.html.haml

%h2 Details about #{@movie.title}

%ul#details
  %li
    Rating:
    = @movie.rating
  %li
    Released on:
    = @movie.release_date.strftime("%B %d, %Y")

  %li
    Director:
    = @movie.director

%h3 Description:

%p#description= @movie.description

= link_to 'Edit', edit_movie_path(@movie)
= button_to 'Delete', movie_path(@movie), :method => :delete, :confirm => 'Are you sure?'
= link_to 'Back to movie list', movies_path
= link_to 'Find Movies With Same Director', samed_path(:title => @movie.title, :director => @movie.director)